spring:
  profiles: stage
user:
  userName: Henry-stage
  sex: male
  age: 18
book:
  name: SpringCloudInAction
  author: ZhaoYongChao
  desc: ${book.author} is writing <${book.name}>
server:
  port: 8080