spring:
  profiles: prod
user:
  userName: Henry-prod
  sex: male
  age: 18
book:
  name: SpringCloudInAction
  author: ZhaoYongChao
  desc: ${book.author} is writing <${book.name}>
  id: ${random.int}
server:
  port: 8080